version: '3'

networks:
  samplesbootnetwork:
    driver: bridge

volumes:
  samplesboot-nexus-data:
  samplesboot-jenkins-data:
  samplesboot-db-data:
  samplesboot-static-data:

services:
  nexus:
    image: sonatype/nexus:latest
    volumes:
      - "samplesboot-nexus-data:/sonatype-work"
    ports:
      - 8081:8081
    networks:
      - samplesbootnetwork
    container_name: samplesboot-nexus
  sonarqube:
    image: library/sonarqube:lts-alpine
    networks:
      - samplesbootnetwork
    ports:
      - 9000:9000
      - 9092:9092
    container_name: samplesboot-sonarqube
  jenkins:
    build: jenkins
    networks:
      - samplesbootnetwork
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: samplesboot-jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "samplesboot-jenkins-data:/var/jenkins_home"
      - "samplesboot-static-data:/var/statics"
    depends_on:
      - sonarqube
  mysql:
    image: library/mysql:8.0
    container_name: samplesboot-mysql
    privileged: true
    volumes:
      - "samplesboot-db-data:/var/lib/mysql"
    ports:
      - 3306:3306
      - 33060:33060
    restart: always
    networks:
      - samplesbootnetwork
    environment:
      MYSQL_ROOT_PASSWORD: "autentia.samples"
      MYSQL_DATABASE: "samplesboot"